import type { Metadata } from 'next'
import '@/app/globals.css'
import { Flower1, Flower2 } from '@/app/components/svg/flower';
import { platypi } from '@/app/components/ui/fonts';
import Link from 'next/link';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const year = new Date().getFullYear()
  const copyrightYear = year > 2024 ? `2024-${year}` : '2024'
  const isAdmin = true

  return (
    <html lang="en" className={`flex flex-col size-full items-stretch ${platypi.className}`}>
      <body className="flex flex-col flex-grow items-stretch bg-theme-light-brown">
        <Flower1
          className="fixed -z-10 fill-theme-green bottom-0 right-1/4 scale-150 rotate-12
          lg:translate-x-32
          translate-x-64"
        />
        <Flower2
          className="fixed -z-10 fill-theme-brown top-64 left-1/4 scale-150 -rotate-12
          lg:-translate-x-32
          -translate-x-64
          sm:block
          hidden"
        />
        <main className="flex-grow pb-12 size-full flex flex-col items-center md:px-16 sm:px-8 px-0">
          <div className="flex flex-col items-center size-full max-w-screen-lg relative">{children}</div>
        </main>
        <footer className="flex justify-center gap-4 bg-theme-white text-sm text-graphite shadow-xl">
          <span>© {copyrightYear} All rights reserved</span>
          <span>|</span>
          <Link href="/admin" className="underline">Admin</Link>
          <span>|</span>
          <Link href="/legal" className="underline">Legal</Link>
        </footer>
      </body>
    </html>
  );
}
